version: '3.9'

services:
  express-backend:
    container_name: express-backend
    image: 'load-balance-be'
    stdin_open: true
    tty: true
  
  react-frontend:
    container_name: load-balance-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=development
    depends_on:
      - express-backend
